### ISSUE TITLE
Error in coordinate conversion -  TypeError: missing a required argument: 'z'

### ISSUE THREAD

**Issue by jasonkodish** [einsteinpy/einsteinpy#601] opened 2022-05-23 20:33 UTC
Ran this: import numpy as np
from astropy import units as u
from einsteinpy.coordinates import BoyerLindquistDifferential, CartesianDifferential, Cartesian, BoyerLindquist

Then this: 
a = 0.5 * u.km

pos_vec = Cartesian(.265003774 * u.km, -153.000000e-03 * u.km,  0 * u.km)

bl_pos = pos_vec.to_bl(a)
print(bl_pos)

cartsn_pos = bl_pos.to_cartesian(a)
print(cartsn_pos)

pos_vel_coord = CartesianDifferential(.265003774 * u.km, -153.000000e-03 * u.km,  0 * u.km,
                          145.45557 * u.km/u.s, 251.93643748389 * u.km/u.s, 0 * u.km/u.s)

bl_coord = pos_vel_coord.bl_differential(a)
bl_coord = bl_coord.si_values()
bl_vel = bl_coord[3:]
print(bl_vel)

cartsn_coord = bl_coord.cartesian_differential(a)
cartsn_coord = cartsn_coord.si_values()
cartsn_vel = cartsn_coord[3:]
print(cartsn_vel)

Got this error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [9], in <cell line: 3>()
      1 a = 0.5 * u.km
----> 3 pos_vec = Cartesian(.265003774 * u.km, -153.000000e-03 * u.km,  0 * u.km)
      5 bl_pos = pos_vec.to_bl(a)
      6 print(bl_pos)

File ~/gwpy/venv/lib/python3.9/site-packages/astropy/units/decorators.py:231, in QuantityInput.__call__.<locals>.wrapper(*func_args, **func_kwargs)
    228 @wraps(wrapped_function)
    229 def wrapper(*func_args, **func_kwargs):
    230     # Bind the arguments to our new function to the signature of the original.
--> 231     bound_args = wrapped_signature.bind(*func_args, **func_kwargs)
    233     # Iterate through the parameters of the original signature
    234     for param in wrapped_signature.parameters.values():
    235         # We do not support variable arguments (*args, **kwargs)

File /usr/lib/python3.9/inspect.py:3045, in Signature.bind(self, *args, **kwargs)
   3040 def bind(self, /, *args, **kwargs):
   3041     """Get a BoundArguments object, that maps the passed `args`
   3042     and `kwargs` to the function's signature.  Raises `TypeError`
   3043     if the passed arguments can not be bound.
   3044     """
-> 3045     return self._bind(args, kwargs)

File /usr/lib/python3.9/inspect.py:2960, in Signature._bind(self, args, kwargs, partial)
   2958                 msg = 'missing a required argument: {arg!r}'
   2959                 msg = msg.format(arg=param.name)
-> 2960                 raise TypeError(msg) from None
   2961 else:
   2962     # We have a positional argument to process
   2963     try:

TypeError: missing a required argument: 'z'

**Comment by JeS24** [comment] 2022-10-28 09:07
Another issue caused by outdated docs. It's fixed now. Ensure that you are on `einsteinpy>=0.4.0` and consult the updated docs at https://docs.einsteinpy.org/en/latest/user_guide.html.

**Closed by JeS24** 2022-10-28 09:07 UTC
Labels: documentation
