### ISSUE TITLE
RuntimeError: Failed to converge after 50 iterations, value is nan.

### ISSUE THREAD

**Issue by adamdarx** [einsteinpy/einsteinpy#636] opened 2023-09-16 02:16 UTC
🐞 **Problem**
When I reproduced the code in https://docs.einsteinpy.org/en/latest/examples/Shadow%20cast%20by%20a%20thin%20emission%20disk%20around%20a%20Schwarzschild%20black%20hole.html, my code reported this error.

According to the traceback, it was actually a error raised by SciPy when EinsteinPy wanted to find a root of a certain equation. But the official website tells me it should work and normally show a graph about intensity.

🖥 **Please paste the output of following commands**
Traceback (most recent call last):
  File "C:\Users\LENOVO\PycharmProjects\grProj\example_set2\shadowcast.py", line 9, in <module>
    shadow = Shadow(mass=mass, fov=fov, n_rays=100)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\PycharmProjects\grProj\venv\Lib\site-packages\astropy\units\decorators.py", line 313, in wrapper
    return_ = wrapped_function(*func_args, **func_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\PycharmProjects\grProj\venv\Lib\site-packages\einsteinpy\rays\shadow.py", line 29, in __init__
    root = newton(self._root_equation, 0.1, args=(i,))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\PycharmProjects\grProj\venv\Lib\site-packages\scipy\optimize\_zeros_py.py", line 381, in newton
    raise RuntimeError(msg)
RuntimeError: Failed to converge after 50 iterations, value is nan.

**Comment by JeS24** [comment] 2023-09-16 15:58
@adamdarx Thank you for the opening the issue. I can confirm this error with both `einsteinpy==0.4.0` (stable) and `einsteinpy==0.5.dev0` (latest).

**Comment by JeS24** [comment] 2023-09-17 14:32
@adamdarx This issue seems to have been introduced due to code changes in `scipy==1.11.0`. If possible, you can downgrade to `scipy==1.10.1` as a temporary measure.

Also see: https://github.com/einsteinpy/einsteinpy/issues/637 (duplicate of this issue).

**Closed** 2023-09-22 13:36 UTC
Labels: bug, rays
